language: python
sudo: false
python:
  - "3.4"

addons:
  apt:
    packages:
    - g++
    - gfortran
    - liblapack-dev
    - libopenblas-dev
    - python3-dev
    - enchant

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - ls -l /home/travis/miniconda3/bin
  - conda update --yes conda

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
  - python --version
  - python -c "import numpy;print(numpy.__version__)"
  - python -c "import scipy;print(scipy.__version__)"
  - touch /home/travis/miniconda3/lib/python3.4/site-packages/easy-install.pth
  - travis_wait pip install -r requirements.txt || date
  - python -m nltk.downloader stopwords
  - pip install codecov

# command to run tests
script:
  - nosetests -v --with-coverage --cover-package=wb_vandalism

after_success:
  - codecov

notifications:
  email:
    recipients:
      - Ladsgroup@gmail.com
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
